engines:
  rubocop:
    enabled: false
  golint:
    enabled: false
  eslint:
    enabled: true
    channel: "eslint-3"
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
ratings:
  paths:
  - src/**
exclude_paths:
- lib/**/*
- test/**/*
- coverage/**/*
- .nyc_output/**/*
