language: node_js
node_js:
  - 6.10.2
branches:
  only:
    - /.*/
before_script:
  - npm install
script:
  - npm run coverage
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
